name: poi_server
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - cudatoolkit=11.8
  - numpy
  - opencv
  - pip:
    - fastapi==0.104.1
    - uvicorn==0.24.0
    - facenet-pytorch==2.5.2
    - motpy==0.0.8
    - pydantic==2.5.2
    - python-multipart==0.0.6 